/**
 * Die folgende Liste stellt eine Liste von Wörtern dar, die in der Spracherkennung erkannt werden.
 * - Wörter, die in der Liste vorkommen, werden auch in der Spracherkennung erkannt.
 * - Wörter, die nicht in der Liste vorkommen, werden von der Spracherkennung nicht erkannt.
 * - Es können auch Umlaute verwendet werden.
 * - Wörter können auch aus Listen mit Alternativwörtern bestehen. Das erste Wort der Alternativliste wird als erkanntes Wort der Grammatik übergeben.
 */
window.SPEECH_CONFIG.wordlist = [
  "alexa",
  "bibi",
  "harry",
  "navigate",
  "to",
  "geh",
  "gehe",
  "befehle",
  "hilfe",
  "weiter",
  "zurück",
  "navigiere",
  "zu",
  "recherche",
  "test",
  "on",
  "an",
  "aus",
  "ein",
  "off",
  "schalte",
  "turn",
  "anzeigen",
  "verstecken",
  "voice",
  "sprache",
  "wähle",
  "selektiere",
  "klicke",
  "klick",
  ["sitemap", "site map"],
  ["sprachassistent", "sprach assistent"],
  "qualität",
  ["1", "eins"],
  ["2", "zwei"],
  ["3", "drei"],
  ["4", "vier"],
  ["5", "fünf"],
  "bestätigen",
  "quiz",
  "videos",
  "video",
  "spiele",
  "spiel",
  "halte",
  "stoppe",
  ["stop", "stopp"],
  "play",
  "pause",
  "pausiere",
  "antwort",
  "auswählen",
  "abwählen",
  "einstellungen",
  "impressum",
  "abbrechen",
  "beenden",
  "stoppen",
  "wechsle zu",
  "untertitel",
  "menü",
  "modus",
  "modul",
  "wählen",
  "starten",
  "plagiat",
  "oder",
  "fehler",
  ["plagiatsformen", "plagiats formen", "plagiat formen", "plagiat form"],
  ["plagiatserkennung", "plagiats erkennung", "plagiat erkennung"],
  "plagiieren",
  "verhindern",
  "übersicht",
  "richtig",
  "falsch",
  "fortfahren",
  "abschicken",
  "bestätigen",
  "ja",
  "nein",
  "home",
  "kapitel",
  "informationen",
  ["sprachbefehle", "sprach befehle"],
  "wechseln",
  "name",
  "ändern",
  "anrede",
  "ressourcen",
  "wissen",
  "check",
  ["wissenscheck", "wissens check", "wissen check"],
];
