/**
 * Die folgende Liste stellt eine Liste von Wörtern dar, die in der Spracherkennung erkannt werden.
 * - Wörter, die in der Liste vorkommen, werden auch in der Spracherkennung erkannt.
 * - Wörter, die nicht in der Liste vorkommen, werden von der Spracherkennung nicht erkannt.
 * - Es können auch Umlaute verwendet werden.
 * - Wörter müssen die Groß- und Kleinschreibung der Grammatik beachten.
 */
window.SPEECH_CONFIG.wordlist = [
  "alexa",
  "bibi",
  "harry",
  "navigate",
  "to",
  "geh",
  "gehe",
  "befehle",
  "hilfe",
  "weiter",
  "zurück",
  "navigiere",
  "zu",
  "recherche",
  "test",
  "on",
  "an",
  "aus",
  "ein",
  "off",
  "schalte",
  "turn",
  "voice",
  "sprache",
  "wähle",
  "selektiere",
  "klicke",
  "klick",
  "site map",
  "sprach assistent",
  "recherche tipps",
  "grundlagen des wissenschaftlichen arbeitens",
  "basis funktionen",
  "such tools",
  "such strategie",
  "qualität",
  "a",
  "b",
  "c",
  "d",
  "eins",
  "zwei",
  "drei",
  "vier",
  "fünf",
  "bestätigen",
  "quiz",
  "videos",
  "video",
  "spiele",
  "spiel",
  "halte",
  "stoppe",
  "stop",
  "play",
  "pause",
  "pausiere",
  "antwort",
  "auswählen",
  "abwählen",
  "einstellungen",
  "impressum",
  "abbrechen",
  "beenden",
  "stoppen",
  "wechsle zu",
  "untertitel",
  "menü",
];
